### ISSUE TITLE
Add Sprint Results to races with Sprints

### ISSUE THREAD

**Issue by brombomb** [brombomb/f1hub#41]
New to last season are sprint Saturday's on some race weekends.  These should have links from the main page, and a results page

**Comment by ayush-wd** [comment]
Sir, I can work on this issue.

**Comment by brombomb** [comment]
Send a MR over :)

**Comment by ayush-wd** [comment]
sure sir

**Comment by ayush-wd** [comment]
![image](https://user-images.githubusercontent.com/83002299/183620748-90d738ca-685a-4d6c-a7a9-73adb7b027c4.png)

1) Sir I think it would look better and more uniform if all the driver names along with their flags were aligned to the left and then centered instead of centering them in the beginning.  If this is all right by you I can do the same for all the other fields where it's necessary. 

2) Sir I think the constructor names in the driver standings page should also be converted to links. This will enhance the UX of the webpage and make it easier for the user to navigate to the respective constructors' wiki page.

![image](https://user-images.githubusercontent.com/83002299/183621139-4f81814f-785b-4d7c-9053-42de13abaff5.png)

**Comment by ayush-wd** [comment]
Should I send a merge request for this sir?

**Comment by brombomb** [comment]
This looks good to me. Either a separate MR or included in the sprint race one

**Comment by ayush-wd** [comment]
Sent a MR for the 2nd issue

**Comment by ayush-wd** [comment]
Should I also send a MR for the alignment enhancement.

**Comment by brombomb** [comment]
Yes please send any MRs and keep them separate if possible. Best practice. I appreciate the formality, of sir, but it really isn't necessary.

Thanks for contributing

**Comment by ayush-wd** [comment]
sure

**Comment by brombomb** [comment]
I liked your work so much I went ahead and removed all center text alignment.  It's a better table practice anyway.

**Comment by ayush-wd** [comment]
Thank you sir

**Comment by ayush-wd** [comment]
Sir I am trying to contribute, I am getting the same errors again and again

**Comment by brombomb** [comment]
What errors are you getting?  Where?

**Comment by ayush-wd** [comment]
While trying to merge my pull request sir

**Comment by brombomb** [comment]
What errors are you seeing?  More details or screenshots would be great.  I already merged your wiki urls

**Comment by ayush-wd** [comment]
![image](https://user-images.githubusercontent.com/83002299/184069402-fb94fcc0-92a7-4d99-b286-472f04e29fa4.png)
The merge request is getting this error.
